version: '3.7'

services:
  web:
    stdin_open: true
    tty: true
    image: "mmmikem/car-wash-app:0.0.5"
    #image: "car-wash-app:0.0.5"
    ports:
      - "3001:3000"
    env_file:
      - .env.development
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  bundle:
