version: '3.7'

services:
  web:
    image: "mmmikem/car-wash-app:staging"
    ports:
      - "3001:3000"
    env_file:
      - .env.development
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: db_password
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
